import = ["/home/sisoyyo/.config/alacritty/cool_theme.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"
